title: Ryan Pek # your name (or website title) here
logo: "/images/pfp2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Male, 19 Years Old<br>
  <br>Singapore<br>
  <br>Student in Temasek Junior College<br>
  
theme: jekyll-theme-minimal
google_analytics: UA-158589894-1 # your Google Analytics tracking ID here
